### ISSUE TITLE
Error encountered when trying to build the site on windows

### ISSUE THREAD

**Issue by ynx0** [urbit/urbit.org#1227]
Stack trace
```
Error: The provided path `\docs\development` does not match the page: `/docs/[[...slug]]`.
    at C:\Users\lux\Documents\coding\urbit\urbit.org\node_modules\next\dist\build\utils.js:18:422
    at Array.forEach (<anonymous>)
    at buildStaticPaths (C:\Users\lux\Documents\coding\urbit\urbit.org\node_modules\next\dist\build\utils.js:16:1255)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'Error'
}
Error: The provided path `\docs\development` does not match the page: `/docs/[[...slug]]`.
    at C:\Users\lux\Documents\coding\urbit\urbit.org\node_modules\next\dist\build\utils.js:18:422
    at Array.forEach (<anonymous>)
    at buildStaticPaths (C:\Users\lux\Documents\coding\urbit\urbit.org\node_modules\next\dist\build\utils.js:16:1255)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  type: 'Error'
}
```
Node: 16.13.0
NPM: 8.1.1

Stuff I did
```
npm install
npm run dev

GET http://localhost:3000/docs
```

It seems to be choking on windows paths being delimted with `\` at first glance.

**Comment by matildepark** [comment]
Seems like [you're supposed to do this under WSL](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nextjs-on-wsl)?
